<?php
/**
 * Created by PhpStorm.
 * User: LyubimovBR
 * Date: 12.04.2018
 * Time: 12:43
 */

namespace app\controllers;

use app\models\LoginuForm;
use yii;
use app\models\Users;
use yii\web\Controller;
use yii\widgets\ActiveForm;

class TestController extends Controller
{

    public function actionIndex()
    {
        $model = new Users();
        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = yii\web\Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            if (!$model->validate() === true ) {
                Yii::$app->session->setFlash('kal', "Повезёт в другой раз");
                return $this->render('index', ['model' => $model]);   // TODO: Change the autogenerated stub
            }else {
                Yii::$app->session->setFlash('success1', "Регистрация прошла успешно");
                $model->save();
                return $this->refresh();
            }
        }
        return $this->render('index', ['model' => $model]);   // TODO: Change the autogenerated stub
    }

    public function actionLogin()
    {
        $model = new LoginuForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate() && $model->validatePassword())
            {
                Yii::$app->session->setFlash('kal', "Вроде как авторизировался");
                $model->login();
                return $this->refresh();
            }
            else
            {
                Yii::$app->session->setFlash('errors', "Проверте введённые данные");
                return $this->render('login', ['model' => $model]);
            }
        }

        return $this->render('login', ['model' => $model]);
    }

}